

OBJECTS = Anagram.v2.c
CC = gcc
OPTIONS_1 = -g -W -Wall
OPTIONS_2 = -g -Wall
BIN = Anagram.exe

##########################

$(BIN): $(OBJECTS)
	$(CC) $(OPTIONS_2) -o $(BIN) $(OBJECTS)

# arbol.o: arbol.c pinta.h
	# $(CC) $(OPCIONES) -c arbol.c

# pinta.o: pinta.c pinta.h
	# $(CC) $(OPCIONES) -c pinta.c

clean:
	rm *.o

###########################
# mingw32-make
